name: Testing NuGet Sign
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: '0 15 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout twilio-csharp
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Build & Test
        run: make test
        
  import-certificate:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - run: make install
     - name: import-certificate
       run: |
        New-Item -ItemType directory -Path certificate
        Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
        certutil -decode certificate\certificate.txt certificate\certificate.pfx
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
         name: certificate.pfx
         path: certificate\certificate.pfx
         retention-days: 1
        

  deploy:
    name: Deploy
    needs: [ test, import-certificate ]
    runs-on: ubuntu-latest
    steps:
      - name: Download code signing certificate
        uses: actions/download-artifact@v3
        with:
          name: certificate.pfx
          
      - name: Checkout twilio-csharp
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
          
      - name: Publish package to NuGet
        run: |
         make release
         dotnet nuget sign **/*.nupkg --certificate-path /home/runner/work/twilio-csharp/twilio-csharp/certificate.pfx --certificate-password ${{ secrets.CERTIFICATE_PASSWORD }} --timestamper http://timestamp.digicert.com
          
        
